### PR TITLE
Enable Multilingual

### PR DESCRIPTION
**Pull request by ryugibo**
hello.

I tried applying hugo mulilingual.

this is sample site and config file.
https://ryugibo.github.io/cv/
https://github.com/ryugibo/cv/blob/master/config.toml

thank you

I referenced below links.
https://gohugo.io/extras/aliases#multilingual-example
https://gohugo.io/content/multilingual/

### CODE REVIEW

**Comment by koyakimu** [comment]
Hello, @ryugibo 

I think this pull request is useful to non-English-speaking world developer (like me).
However, I can't use it because I can't get your "config.toml" file.
Could you add your "config.toml" file, too?

**Comment by ryugibo** [comment]
hello, @kimyan .

sorry for late reply.

i fixed my sample cv page and config.toml links.

you can see config.toml and sample page below links.
https://ryugibo.github.io/cv/
https://github.com/ryugibo/cv/blob/master/config.toml

if you want using your language in sub titles, please create your language file to [`i18n`](https://github.com/ryugibo/hugo-orbit-theme/tree/master/i18n) directory.

thank you.

**Comment by aerohub** [comment]
@ryugibo great work!

**Comment by koyakimu** [comment]
Hello, @ryugibo and @aerohub .

@ryugibo , Sorry for late reply, too.
I was going to reply after using your commit, but I have to reply because we have a glad thing that your commit is merged!

I greatly appreciate @aerohub 's and @ryugibo 's work!

**Pull request merged**
